apiVersion: v1
kind: Pod
metadata:
  labels:
    app: secretvisualiser
    aadpodidbinding: matrix
  name: secretvisualiser
spec:
  containers:
  - name: secretvisualiser
    image: pascalnaber/secretvisualiser:1
    volumeMounts:
    - name: test
      mountPath: /kvmnt
      readOnly: true
  volumes:
  - name: test
    flexVolume:
      driver: "azure/kv"
      options:
        usepodidentity: "true"         # [OPTIONAL] if not provided, will default to "false"
        keyvaultname: "matrix-secrets-dev"               # the name of the KeyVault
        keyvaultobjectnames: "Secret1;Secret2"        # list of KeyVault object names (semi-colon separated)
        keyvaultobjecttypes: "secret;secret"    # list of KeyVault object types: secret, key or cert (semi-colon separated)
        keyvaultobjectversions: ""     # [OPTIONAL] list of KeyVault object versions (semi-colon separated), will get latest if empty
        resourcegroup: "matrix-dev-keyvault"              # the resource group of the KeyVault
        subscriptionid: "186d83fa-fddb-4637-a762-918a4cc06ee0"             # the subscription ID of the KeyVault
        tenantid: "0585cdbb-3b95-4277-ad62-77e94847db9e"                   # the tenant ID of the KeyVault
---
apiVersion: v1
kind: Service
metadata:
  name: secret-service
spec:
  ports:
    - port: 80
  selector:
    app: secretvisualiser
  type: LoadBalancer