apiVersion: v1
kind: ServiceAccount
metadata:
  name: tiller-serviceaccount
  namespace: kube-system

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller-clusterrole
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: tiller-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: tiller-serviceaccount
  namespace: kube-system
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: tiller-clusterrole
  apiGroup: rbac.authorization.k8s.io